# Generated by Django 2.2.3 on 2019-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searchstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=1000)),
                ('sub_date', models.DateTimeField(verbose_name='time submitted')),
                ('match', models.CharField(max_length=1000)),
            ],
        ),
    ]
