# Generated by Django 2.2.3 on 2019-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchstr',
            name='task_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
